name: 🐍 AI Engineer Snake Game

on:
  # Schedule the workflow to run daily at midnight UTC
  schedule:
    - cron: "0 0 * * *"
  # Allow manual triggering of the workflow
  workflow_dispatch:
  # Trigger the workflow on pushes to the main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Generate the snake animations with AI/ML themed colors
      - name: Generate AI Engineer Snake Animations
        uses: Platane/snk@v3
        with:
          # GitHub username to generate the animation for
          github_user_name: ${{ github.repository_owner }}
          # Define the output files and their configurations
          outputs: |
            dist/github-snake.svg?color_snake=#36BCF7&color_dots=#1e3a8a,#3b82f6,#60a5fa,#93c5fd,#dbeafe
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#00d4aa&color_dots=#0d9488,#14b8a6,#2dd4bf,#5eead4,#99f6e4
            dist/ai-snake.svg?color_snake=#8b5cf6&color_dots=#581c87,#7c3aed,#8b5cf6,#a78bfa,#c4b5fd
            dist/ml-snake.svg?color_snake=#f59e0b&color_dots=#92400e,#d97706,#f59e0b,#fbbf24,#fde68a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Deploy the generated files to the 'output' branch
      - name: Deploy AI Snake Animations
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          # Custom commit message for AI theme
          commit_message: "🤖 Update AI Engineer snake animations [skip ci]"
